from django.urls import path
from . import views as store_views



urlpatterns = [
    path('', store_views.home, name='bookstore-home'),
    path('product/<slug>/',store_views.ItemDetailView.as_view(), name='product-detail'),
    path('order-summary/', store_views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', store_views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', store_views.remove_from_cart, name='remove-from-cart'),
    path('add-to-wishlist/<slug>/', store_views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist/<slug>/', store_views.remove_from_wishlist, name='remove-from-wishlist'),
    path('my-wishlist/', store_views.my_wishlist, name='my-wishlist'),
    path('remove-single-item-from-cart/<slug>/', store_views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('add-coupon/', store_views.AddCouponView.as_view(), name='add-coupon'),
    path('author/<str:author>/', store_views.AuthorBookList, name='author-books'),
    path('category/<str:category>/', store_views.CategoryBookList, name='category-books'),
    path('tag/<slug:slug>/', store_views.tagged, name='tagged'),
    path('add-book/', store_views.add_book, name='add-book'),
    path('my-orders/', store_views.my_orders, name='my-orders'),
    path('profile/', store_views.profile, name='profile'),
    path('add-seller/', store_views.add_seller, name='add-seller'),
    path('about-us/', store_views.about_us, name="about-us"),
    path('terms-and-conditions/', store_views.terms_and_conditions, name="terms-and-conditions"),
    path('privacy/', store_views.privacy, name="privacy"),
    path('refunds-cancellation/', store_views.refunds_cancellation, name="refunds-cancellation"),
    path('update-book/<slug>/', store_views.update_book, name='update-book'),
    path('order-placed/<payment_id>/', store_views.order_placed, name='order-placed'),
    path('seller-order-details/<payment_id>/', store_views.seller_order_details, name="seller_order_details"),
    path('request-refund/<payment_id>/', store_views.request_refund, name="request-refund"),
    path('grant-refund/<payment_id>/', store_views.grant_refund, name="grant-refund"),
    path('my-orders/', store_views.my_orders, name='my-orders'),
    path('seller-sale/', store_views.seller_sale, name="seller-sale"),
    path('checkout/', store_views.CheckoutView.as_view(), name='checkout'),
    path('refunds-cancellation/', store_views.refunds_cancellation, name="refunds-cancellation"),
    path('payment/', store_views.payment, name='payment'),
    path('payment-success/', store_views.payment_success, name='payment-success'),
    path('add-seller/', store_views.add_seller, name='add-seller'),
    path('seller-books/', store_views.SellerBooks.as_view(), name='seller-books'),
    path('add-referal/', store_views.AddReferalView.as_view(), name='add-referal'),
    path('search-result/<str:search>/', store_views.search_result, name="search-result"),
    path('activate-sellers-account/', store_views.activate_sellers_account, name='activate-sellers-account'),
]